name : CI/CD Pipeline

on: 
  push:
    branches:
       -main


       jobs:
       build-and-deploy:
         runs-on :ubuntu-latest

          steps:
            -name:checkout code
            uses:action/checkout@v2

            -name: setup Node.js
            uses:action/setup-node@v2
            with:
            node-version: '16'

            -name:run test
            run:npm test

            -name:build project
            run npm run build

            -name: deploy project
            run: echo "finally ci/cd complete"
